#!/usr/bin/env bash

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "master" ] || [ "$branch" = "main" ]; then
  echo "❌ You are on $branch! Please create a feature branch."
  exit 1
fi

npx --no-install lint-staged
